# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: freeislet@gmail.com
author_name: Sunghwan Kang
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupyterlab-double-sharp
mimetype: ''
mimetype_name: ''
project_short_description: 'Jupyterlab extension that provides features like execution cache, auto-dependency, external file loading and more.'
python_name: jupyterlab_double_sharp
repository: https://github.com/freeislet/jupyterlab-double-sharp
test: true
viewer_name: ''
